# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/158AydOvyYALd9NTMqjLM-dVV9Of-vawl
"""

from github import Github

# Replace with your GitHub access token
g = Github("YOUR_ACCESS_TOKEN")

# Replace with your desired repository name and description
repo_name = "My New Repository"
repo_description = "This is a new repository created by my Telegram bot."

# Create the new repository on your account
user = g.get_user()
repo = user.create_repo(repo_name, description=repo_description)

# Upload a sample file to the repository
contents = "This is a sample file created by my Telegram bot."
repo.create_file("README.md", "Initial commit", contents)